export default {
  content: [ './index.html', './src/**/*.{vue,js,ts,jsx,tsx}' ],
  safelist: [
    `bg-[url('@/assets/images/background/bg00.webp')]`,
    `bg-[url('@/assets/images/background/bg01.webp')]`,
    `bg-[url('@/assets/images/background/bg02.webp')]`, 
    `bg-[url('@/assets/images/background/bg03.webp')]`, 
    `bg-[url('@/assets/images/background/bg04.webp')]`, 
    `bg-[url('@/assets/images/background/bg05.webp')]`, 
    `bg-[url('@/assets/images/background/bg06.webp')]`, 
    `bg-[url('@/assets/images/background/bg07.webp')]`, 
    `bg-[url('@/assets/images/background/bg08.webp')]`, 
    `bg-[url('@/assets/images/background/bg09.webp')]`, 
  ],
  theme: {
    extend: {
      colors: {
        // Configure your color palette here
        red: '#AE0000',
        'red-dark': '#730000',
        pink: '#EC7DD3',
        purple: '#8962F8',
        skyblue: '#7195F2',
        grassgreen: '#68C907',
        yellow: '#EACA24',
        'yellow-other': '#FFE55A',
        'yellow-bright': '#FEE718',
        orange: '#FF8D4D',
        white: '#F7F7F7',
        grey: '#8C8C8C',
        grey50: 'rgba(140, 140, 140, 0.5)',
        grey70: 'rgba(140, 140, 140, 0.7)',
        'grey-deep': '#575757',
        skin: '#FFFFFF',
        white20: 'rgba(255, 255, 255, 0.20)',
        oldBook: '#C8B59F',
      },
    },
  },
  plugins: [],
}