openapi: 3.0.3
info:
  title: 出包魔法師 API
  version: 1.0.0
  
servers:
  - url: https://gaas-magician-backend.azurewebsites.net/
    description: 後端伺服器(自動遊戲狀態推播)
  - url: http://localhost:5000
    description: 本地開發伺服器
  - url: https://gaas-magician.azurewebsites.net/
    description: 後端伺服器(無自動遊戲狀態推播)
# 定義獨立的schema
components:
  schemas:
    GameCreateRequest:
      type: "object"
      properties:
        playerIDs:
          type: "array"
          items:
            type: "string"
      required:
        - playerIDs
      example:
        playerIDs: ["Teds", "Tux", "Yock", "Momo", "Leave3310"]

    GameCreateResponse:
      type: "object"
      properties:
        msg:
          type: "string"
        gameRoomID:
          type: "string"
      required:
        - msg

    GameJoinRequest:
      type: "object"
      properties:
        gameRoomID:
          type: "string"
      required:
        - gameRoomID

    SpellingRequest:
      type: "object"
      properties:
        gameRoomID:
          type: string
        playerID:
          type: string
        spellName:
          type: string
      required:
        - gameRoomID
        - playerID
        - spellName

paths:
  "/gameCreate":
    post:
      summary: "開始遊戲"
      operationId: "GameCreate"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/GameCreateRequest"
      responses:
        "201":
          description: "成功，回傳gameRoomID"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GameCreateResponse"
              examples:
                ExamplePlayersEnough:
                  value:
                    msg: "Game created"
                    gameRoomID: "655564039448700eff367956"
        "400":
          description: "請求失敗，請檢查輸入參數"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/GameCreateResponse"
              examples:
                ExamplePlayersNotEnough:
                  value:
                    msg: "Number of players must be greater than 3"
        
                ExamplePlayersOver5:
                  value:
                    msg: "Number of players cannot exceed 5"
  
  "/player/{playerID}/join":
    put:
      summary: "進入遊戲"
      operationId: "GameJoin"
      parameters:
        - name: "playerID"
          in: "path"
          required: true
          schema:
            type: "string"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/GameJoinRequest"
      responses:
        "200":
          description: "成功"
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  message:
                    type: "string"
                  gameRoomID:
                    type: "string"
        "400":
          description: "Unable to join game"
        "404":
          description: "Player ID required"
  
  "/stone":
    patch:
      summary: "施法"
      operationId: "Spelling"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SpellingRequest"
      responses:
        "200":
          description: "施法結果"
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  message:
                    type: "string"
              examples:
                ExampleSpellSuccessfully:
                  value:
                    message: "Spell cast successfully"
        
                ExampleSpellFailed:
                  value:
                    message: "Spell cast failed"
        "400":
          description: "施法操作不合法"
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  message:
                    type: "string"
              examples:
                ExampleNoGameRoomID:
                  value:
                    message: "gameRoomID is required"
                ExampleNoPlayerID:
                  value:
                    message: "Player ID and spell name are required"
                ExampleNoSpellName:
                  value:
                    message: "Player ID and spell name are required"
                ExampleInvalidSpellOperate:
                  value:
                    message: "Spell cast failed"
  
  "/player/{playerID}/spellstop":
    patch:
      summary: "決定不再施法"
      operationId: "SpellStop"
      parameters:
        - name: "playerID"
          in: "path"
          required: true
          schema:
            type: "string"
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - gameRoomID
              properties:
                gameRoomID:
                  type: string
      responses:
        200:
          description: Player turn ended
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
        400:
          description: Player turn failed
        404:
          description: Player ID is required